### ISSUE TITLE
Everyone can do the Pilotjob without having the Job

### ISSUE THREAD

**Issue by WestyDV** [FA2500/esx_pilot#1]
I tried the script its nice and good , but i want it to work only with the Job is that possible?

**Comment by FA2500** [comment]
Updated the script , do follow the README instructions and change the variable in client.lua , I don't have the means to test it since i no longer active in FiveM , so its up to you to test it whenever it works or not. Feel free to make a PR if you changed it to make it work.

**Comment by WestyDV** [comment]
I tested it and got an error: Error parsing script @esx_pilot/client.lua in resource esx_pilot: @esx_pilot/client.lua:82: ')' expected near '!' .  I am not into scripting i tried myself but i couldn't solve it.

**Comment by FA2500** [comment]
my bad, changed 1 syntax error. Do try again and let me know if it works.

**Comment by WestyDV** [comment]
Now its @esx_pilot/client.lua:75: attempt to index a nil value (global 'ESX')

**Comment by FA2500** [comment]
Huh weird... ESX arent supposed to be nil, well anyway, changed the code to check whenever ESX is nil .

**Comment by FA2500** [comment]
Well since no feedback is received, i assume it work as intended, closing this then. Feel free to reopen if you find anymore bugs.
